version: "3"
services:
  backend:
    build:
      context: backend/
    image: "backend:${tag}"
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=redis
  frontend:
    build: 
      context: frontend/
    image: "frontend:${tag}"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_DNS=backend
    labels:
      kompose.service.type: LoadBalancer
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
