apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./manifests/generated
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./manifests/generated
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - name: backend
          image: 'ghcr.io/stefanowich33/simple-fortune-cookie/cookie-backend:<replaceme>'
          env:
            - name: REDIS_DNS
              value: redis
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
