name: test
on:
  pull_request:
    types: [opened, edited, reopened]

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: $COMMIT_SHA
      - name: Setup golang
        uses: actions/setup-go@v3
        with: 
          go-version: '^1.19'
      - name: Test Backend
        working-directory: ./backend
        run: go test
  test-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: $COMMIT_SHA
      - name: Setup golang
        uses: actions/setup-go@v3
        with: 
          go-version: '^1.19'
      - name: Test Frontend
        working-directory: ./frontend
        run: go test
        
